/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable @next/next/no-img-element */

import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import {url} from './src/baseUrl'

const allData = () => {

    const getEmployee = () => {
        axios.get(`${url}/getEmployees`).then(
            (response) => {
                console.log(response.data)
                setEmployee(response.data)
            },
            (error) => {
                console.log(error)
            }
        )
    }

    useEffect(() => {
        getEmployee();
    }, [])

    const [employee, setEmployee] = useState([]);

    return (
        <>
            <Head>
                <title>All data</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.main}>
                    <h2>All Data</h2>
                    <div className={styles.grid}>
                        {employee.map((emp) => (<div className={styles.card} key={emp.empID}><img src={emp.imageUrl} height={50} width={50} alt="" /><p>{emp.firstName}&nbsp;{emp.lastName}</p><p>{emp.emailId}</p></div>))}
                    </div>
                </div>
            </div>
        </>
    )
}

export default allData