
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Dashboard from './components/Dashboard'
import { url } from './src/baseUrl'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yy1.svg" />
      </Head>
      <Dashboard></Dashboard>
    </>
  )
}
