
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { url } from './src/baseUrl'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Harshbardhan Singh
        </h1>
        <Link href="/allData" className={styles.card}>All Data</Link>
        <Link href="/createData" className={styles.card}>Create data</Link>
        <Link href="/allData" className={styles.card}>Delete Data</Link>
        <Link href="/allData" className={styles.card}>Update Data</Link>
      </main>
    </div>
  )
}
