import { useEffect, useState } from 'react'
import axios from 'axios'
import { url } from '../src/baseUrl'
import styles from '../../styles/dashboard.module.css'
import { BiUser, BiChalkboard } from "react-icons/bi";
import Head from 'next/head';
import { BsFillDropletFill } from "react-icons/bs";
import { VscVmActive } from "react-icons/vsc";
import { Bar, BarChart, CartesianGrid, AreaChart, Area, Legend, Pie, PieChart, ResponsiveContainer, XAxis, YAxis } from 'recharts';
import Charts from '../../template/Charts';
import { Tooltip } from '@nextui-org/react';

const Dashboard = () => {

    const getEmployee = () => {
        axios.get(`${url}/getEmployees`).then(
            (response) => {
                setEmployee(response.data)
            },
            (error) => {
                console.log(error)
            }
        )
    }

    useEffect(() => {
        getEmployee();
        bloodGroup();
        // console.log(bloodGroup())
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    const [employee, setEmployee] = useState([]);
    const [pieData, setPieData] = useState([]);

    const onboardingUser = () => {
        var onboarding = 0;
        employee.map((ele) => {
            ele.status == "onboarding" ? onboarding++ : ""
        })
        return onboarding;
    }
    const activeUser = () => {
        var active = 0;
        employee.map((ele) => {
            ele.status == "active" ? active++ : ""
        })
        return active;
    }
    const awaitingUser = () => {
        var awaiting = 0;
        employee.map((ele) => {
            ele.status == "awaiting" ? awaiting++ : ""
        })
        return awaiting;
    }
    const bloodGroup = () => {
        var ave = 0;
        var bve = 0;
        var ove = 0;
        employee.map((ele) => {
            ele.bloodGroup == "A+" ? ave++ : ele.bloodGroup == "B+" ? bve++ : ove++
        })
        // return `{
        //     A: ${ave},
        //     B: ${bve},
        //     0: ${ove}
        // }`;
        // return `[
        //     {id: 1, A: ${ave}},
        //     {id: 2, B: ${bve}},
        //     {id: 3, 0: ${ove}},
        // ]`;

        // setPieData([
        //     { name: "Facebook", users: 2000000000 },
        //     { name: "Instagram", users: 1500000000 },
        //     { name: "Twiter", users: 1000000000 },
        //     { name: "Telegram", users: 500000000 },
        // ])
        setPieData([
            { id: 1, A: `${ave}` },
            { id: 2, B: `${bve}` },
            { id: 3, 0: `${ove}` },
        ])
        // setPieData([
        //     {
        //       name: 'Page A',
        //       uv: 4000,
        //       pv: 2400,
        //       amt: 2400,
        //     },
        //     {
        //       name: 'Page B',
        //       uv: 3000,
        //       pv: 1398,
        //       amt: 2210,
        //     },
        //     {
        //       name: 'Page C',
        //       uv: 2000,
        //       pv: 9800,
        //       amt: 2290,
        //     },
        //     {
        //       name: 'Page D',
        //       uv: 2780,
        //       pv: 3908,
        //       amt: 2000,
        //     },
        //     {
        //       name: 'Page E',
        //       uv: 1890,
        //       pv: 4800,
        //       amt: 2181,
        //     },
        //     {
        //       name: 'Page F',
        //       uv: 2390,
        //       pv: 3800,
        //       amt: 2500,
        //     },
        //     {
        //       name: 'Page G',
        //       uv: 3490,
        //       pv: 4300,
        //       amt: 2100,
        //     },
        //   ])
    }

    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/yy1.svg" />
            </Head>
            <div className={styles.container_wrapper}>
                <div className={styles.dash_card}>
                    <div className={styles.data}>
                        <div className={styles.fetched_title}>Users</div>
                        <div className={styles.fetched_data}>{employee.length}</div>
                    </div>
                    <div className={styles.data_logo}>
                        <BiUser className={styles.logo} />
                    </div>
                </div>
                {/* <div className={styles.dash_card}>
                    <div className={styles.data}>
                        <div className={styles.fetched_title}>Blood Group</div>
                        <div className={styles.fetched_data}>{employee.length}</div>
                    </div>
                    <div className={styles.data_logo}>
                        <BsFillDropletFill className={styles.logo} />
                    </div>
                </div> */}
                <div className={styles.dash_card}>
                    <div className={styles.data}>
                        <div className={styles.fetched_title}>Onboarding</div>
                        <div className={styles.fetched_data}>{onboardingUser()}</div>
                    </div>
                    <div className={styles.data_logo}>
                        <BiChalkboard className={styles.logo} />
                    </div>
                </div>
                <div className={styles.dash_card}>
                    <div className={styles.data}>
                        <div className={styles.fetched_title}>Active</div>
                        <div className={styles.fetched_data}>{activeUser()}</div>
                    </div>
                    <div className={styles.data_logo}>
                        <VscVmActive className={styles.logo} />
                    </div>
                </div>
                <div className={styles.dash_card}>
                    <div className={styles.data}>
                        <div className={styles.fetched_title}>Awaiting</div>
                        <div className={styles.fetched_data}>{awaitingUser()}</div>
                    </div>
                    <div className={styles.data_logo}>
                        <VscVmActive className={styles.logo} />
                    </div>
                </div>
                {/* <ResponsiveContainer width={700} height="80%">

                </ResponsiveContainer> */}
                {/* <BarChart
                    width={500}
                    height={300}
                    data={data}
                    margin={{
                        top: 5,
                        right: 30,
                        left: 80,
                        bottom: 5,
                    }}
                    barSize={20}
                >
                    <XAxis
                        dataKey="name"
                        scale="point"
                        padding={{ left: 10, right: 10 }}
                    />
                    <YAxis />
                    <Tooltip />
                    <Legend />
                    <CartesianGrid strokeDasharray="3 3" />
                    <Bar dataKey="users" fill="#8884d8" background={{ fill: "#eee" }} />
                </BarChart> */}
                {/* <PieChart width={400} height={400}>
                    <Pie
                        dataKey="id"
                        isAnimationActive={false}
                        data={pieData}
                        cx={200}
                        cy={200}
                        outerRadius={80}
                        fill="#8884d8"
                        label
                    />
                    <Tooltip />
                </PieChart> */}
                {/* <Charts /> */}
                {/* {setTimeout(() => {<AreaChart data={pieData}/>}, 2000)} */}
                {/* <AreaChart width={400} height={400} data={pieData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="uv" />
                    <YAxis />
                    <Tooltip />
                    <Area type="monotone" dataKey="uv" stroke="#8884d8" fill="#8884d8" />
                </AreaChart> */}
                <Charts data={pieData}/>
            </div>
        </>
    )
}

export default Dashboard